/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BookingFlightIdRouteImport } from './routes/booking.$flightId'
import { Route as ConfirmationOrderIdRouteImport } from './routes/confirmation.$orderId'
import { Route as DestinationsIndexRouteImport } from './routes/destinations.index'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as FlightsIndexRouteImport } from './routes/flights.index'
import { Route as FlightsFlightIdRouteImport } from './routes/flights.$flightId'
import { Route as BookingFlightIdIndexRouteImport } from './routes/booking.$flightId.index'
import { Route as BookingFlightIdPassengersRouteImport } from './routes/booking.$flightId.passengers'
import { Route as BookingFlightIdPaymentRouteImport } from './routes/booking.$flightId.payment'
import { Route as BookingFlightIdSeatsRouteImport } from './routes/booking.$flightId.seats'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingFlightIdRoute = BookingFlightIdRouteImport.update({
  id: '/booking/$flightId',
  path: '/booking/$flightId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationOrderIdRoute = ConfirmationOrderIdRouteImport.update({
  id: '/confirmation/$orderId',
  path: '/confirmation/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/destinations/$slug',
  path: '/destinations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsIndexRoute = FlightsIndexRouteImport.update({
  id: '/flights/',
  path: '/flights/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsFlightIdRoute = FlightsFlightIdRouteImport.update({
  id: '/flights/$flightId',
  path: '/flights/$flightId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingFlightIdIndexRoute = BookingFlightIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookingFlightIdRoute,
} as any)
const BookingFlightIdPassengersRoute =
  BookingFlightIdPassengersRouteImport.update({
    id: '/passengers',
    path: '/passengers',
    getParentRoute: () => BookingFlightIdRoute,
  } as any)
const BookingFlightIdPaymentRoute = BookingFlightIdPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => BookingFlightIdRoute,
} as any)
const BookingFlightIdSeatsRoute = BookingFlightIdSeatsRouteImport.update({
  id: '/seats',
  path: '/seats',
  getParentRoute: () => BookingFlightIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/booking/$flightId': typeof BookingFlightIdRouteWithChildren
  '/confirmation/$orderId': typeof ConfirmationOrderIdRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/flights/$flightId': typeof FlightsFlightIdRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/flights/': typeof FlightsIndexRoute
  '/booking/$flightId/passengers': typeof BookingFlightIdPassengersRoute
  '/booking/$flightId/payment': typeof BookingFlightIdPaymentRoute
  '/booking/$flightId/seats': typeof BookingFlightIdSeatsRoute
  '/booking/$flightId/': typeof BookingFlightIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/confirmation/$orderId': typeof ConfirmationOrderIdRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/flights/$flightId': typeof FlightsFlightIdRoute
  '/destinations': typeof DestinationsIndexRoute
  '/flights': typeof FlightsIndexRoute
  '/booking/$flightId/passengers': typeof BookingFlightIdPassengersRoute
  '/booking/$flightId/payment': typeof BookingFlightIdPaymentRoute
  '/booking/$flightId/seats': typeof BookingFlightIdSeatsRoute
  '/booking/$flightId': typeof BookingFlightIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/booking/$flightId': typeof BookingFlightIdRouteWithChildren
  '/confirmation/$orderId': typeof ConfirmationOrderIdRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/flights/$flightId': typeof FlightsFlightIdRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/flights/': typeof FlightsIndexRoute
  '/booking/$flightId/passengers': typeof BookingFlightIdPassengersRoute
  '/booking/$flightId/payment': typeof BookingFlightIdPaymentRoute
  '/booking/$flightId/seats': typeof BookingFlightIdSeatsRoute
  '/booking/$flightId/': typeof BookingFlightIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/dashboard'
    | '/booking/$flightId'
    | '/confirmation/$orderId'
    | '/destinations/$slug'
    | '/flights/$flightId'
    | '/destinations/'
    | '/flights/'
    | '/booking/$flightId/passengers'
    | '/booking/$flightId/payment'
    | '/booking/$flightId/seats'
    | '/booking/$flightId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/dashboard'
    | '/confirmation/$orderId'
    | '/destinations/$slug'
    | '/flights/$flightId'
    | '/destinations'
    | '/flights'
    | '/booking/$flightId/passengers'
    | '/booking/$flightId/payment'
    | '/booking/$flightId/seats'
    | '/booking/$flightId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/dashboard'
    | '/booking/$flightId'
    | '/confirmation/$orderId'
    | '/destinations/$slug'
    | '/flights/$flightId'
    | '/destinations/'
    | '/flights/'
    | '/booking/$flightId/passengers'
    | '/booking/$flightId/payment'
    | '/booking/$flightId/seats'
    | '/booking/$flightId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  DashboardRoute: typeof DashboardRoute
  BookingFlightIdRoute: typeof BookingFlightIdRouteWithChildren
  ConfirmationOrderIdRoute: typeof ConfirmationOrderIdRoute
  DestinationsSlugRoute: typeof DestinationsSlugRoute
  FlightsFlightIdRoute: typeof FlightsFlightIdRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
  FlightsIndexRoute: typeof FlightsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$flightId': {
      id: '/booking/$flightId'
      path: '/booking/$flightId'
      fullPath: '/booking/$flightId'
      preLoaderRoute: typeof BookingFlightIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation/$orderId': {
      id: '/confirmation/$orderId'
      path: '/confirmation/$orderId'
      fullPath: '/confirmation/$orderId'
      preLoaderRoute: typeof ConfirmationOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/destinations/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights/': {
      id: '/flights/'
      path: '/flights'
      fullPath: '/flights/'
      preLoaderRoute: typeof FlightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights/$flightId': {
      id: '/flights/$flightId'
      path: '/flights/$flightId'
      fullPath: '/flights/$flightId'
      preLoaderRoute: typeof FlightsFlightIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$flightId/': {
      id: '/booking/$flightId/'
      path: '/'
      fullPath: '/booking/$flightId/'
      preLoaderRoute: typeof BookingFlightIdIndexRouteImport
      parentRoute: typeof BookingFlightIdRoute
    }
    '/booking/$flightId/passengers': {
      id: '/booking/$flightId/passengers'
      path: '/passengers'
      fullPath: '/booking/$flightId/passengers'
      preLoaderRoute: typeof BookingFlightIdPassengersRouteImport
      parentRoute: typeof BookingFlightIdRoute
    }
    '/booking/$flightId/payment': {
      id: '/booking/$flightId/payment'
      path: '/payment'
      fullPath: '/booking/$flightId/payment'
      preLoaderRoute: typeof BookingFlightIdPaymentRouteImport
      parentRoute: typeof BookingFlightIdRoute
    }
    '/booking/$flightId/seats': {
      id: '/booking/$flightId/seats'
      path: '/seats'
      fullPath: '/booking/$flightId/seats'
      preLoaderRoute: typeof BookingFlightIdSeatsRouteImport
      parentRoute: typeof BookingFlightIdRoute
    }
  }
}

interface BookingFlightIdRouteChildren {
  BookingFlightIdPassengersRoute: typeof BookingFlightIdPassengersRoute
  BookingFlightIdPaymentRoute: typeof BookingFlightIdPaymentRoute
  BookingFlightIdSeatsRoute: typeof BookingFlightIdSeatsRoute
  BookingFlightIdIndexRoute: typeof BookingFlightIdIndexRoute
}

const BookingFlightIdRouteChildren: BookingFlightIdRouteChildren = {
  BookingFlightIdPassengersRoute: BookingFlightIdPassengersRoute,
  BookingFlightIdPaymentRoute: BookingFlightIdPaymentRoute,
  BookingFlightIdSeatsRoute: BookingFlightIdSeatsRoute,
  BookingFlightIdIndexRoute: BookingFlightIdIndexRoute,
}

const BookingFlightIdRouteWithChildren = BookingFlightIdRoute._addFileChildren(
  BookingFlightIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  DashboardRoute: DashboardRoute,
  BookingFlightIdRoute: BookingFlightIdRouteWithChildren,
  ConfirmationOrderIdRoute: ConfirmationOrderIdRoute,
  DestinationsSlugRoute: DestinationsSlugRoute,
  FlightsFlightIdRoute: FlightsFlightIdRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
  FlightsIndexRoute: FlightsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
